### ISSUE TITLE
oracle字段默认值与字段类型不匹配的问题

### ISSUE THREAD

**Issue by Lingoxu1990** [wentaojin/transferdb#10]
您好，在测试的时候发现某个oracle字段类型是number，但是默认值是''。在reverse阶段没有提醒异常。我们是在Tidb建表的时候发现这问题。目前只发现这个异常，不排除我们原始oracle库中存在其他默认值与字段类型不匹配的情况。能否加一层默认值与类型的校验呢？
oracle 版本 12.2.0.1.0

**Comment by wentaojin** [comment]
> 您好，在测试的时候发现某个oracle字段类型是number，但是默认值是''。在reverse阶段没有提醒异常。我们是在Tidb建表的时候发现这问题。目前只发现这个异常，不排除我们原始oracle库中存在其他默认值与字段类型不匹配的情况。能否加一层默认值与类型的校验呢？ oracle 版本 12.2.0.1.0

这种情况有点类似于原本 oracle 建表字段 default null，后期业务变更新增字段检查约束 not null，建表语句会直接 not null default null，创建语句会报错，这个其实程序不好处理，考虑可能已有数据存在了 null，只能手工核对，最多新增类似冲突输出但不处理

**Comment by Lingoxu1990** [comment]
> > 您好，在测试的时候发现某个oracle字段类型是number，但是默认值是''。在reverse阶段没有提醒异常。我们是在Tidb建表的时候发现这问题。目前只发现这个异常，不排除我们原始oracle库中存在其他默认值与字段类型不匹配的情况。能否加一层默认值与类型的校验呢？ oracle 版本 12.2.0.1.0
> 
> 这种情况有点类似于原本 oracle 建表字段 default null，后期业务变更新增字段检查约束 not null，建表语句会直接 not null default null，创建语句会报错，这个其实程序不好处理，考虑可能已有数据存在了 null，只能手工核对，最多新增类似冲突输出但不处理

明白，谢谢
