### ISSUE TITLE
reverse生成的建表语句建议

### ISSUE THREAD

**Issue by Lingoxu1990** [wentaojin/transferdb#11]
能否根据target的数据库类型切换建表的option参数呢？
例如 我目标库是tidb，我希望建表语句加上TiDB的TableOption （SHARD_ROW_ID_BITS = 4 PRE_SPLIT_REGIONS = 4）
如果可以的话，能否根据源表(oracle)的数据量，给出一个最佳的TableOption呢？

**Comment by wentaojin** [comment]
> 能否根据target的数据库类型切换建表的option参数呢？ 例如 我目标库是tidb，我希望建表语句加上TiDB的TableOption （SHARD_ROW_ID_BITS = 4 PRE_SPLIT_REGIONS = 4） 如果可以的话，能否根据源表(oracle)的数据量，给出一个最佳的TableOption呢？

Good Idea，TiDB【SHARD_ROW_ID_BITS = 4 PRE_SPLIT_REGIONS = 4】作用于非整型主键或者没有主键表，直接根据数据量不好给建议，可以考虑非整型主键或者没有主键表统一带 TableOption

**Comment by Lingoxu1990** [comment]
> 整型主键或者没有主键

ORACLE中使用了复合主键的表是否可以直接映射为非聚簇表呢？然后添加上TableOption 。数据量这块确实不太好预估。

**Comment by Lingoxu1990** [comment]
reverse阶段生成建表语句，还有一个建议。
当前我使用的是tidb 5.3.1版本。
ADD INDEX 语句执行很慢（6s左右），我在社区问答中得到一个解决方案是 将索引的创建放在CTEATE TABLE 语句里。这个效率非常高。基本不需要额外的时间来给空表创建索引。
能否考虑对目标数据库是tidb的reverse，不再使用 create table  (col1 ...,cole ... ) ; ADD index .....；
使用create table ( col1 ... , col2 ...    ,    key keyName (col1) )？

**Comment by wentaojin** [comment]
> > > 能否根据target的数据库类型切换建表的option参数呢？ 例如 我目标库是tidb，我希望建表语句加上TiDB的TableOption （SHARD_ROW_ID_BITS = 4 PRE_SPLIT_REGIONS = 4） 如果可以的话，能否根据源表(oracle)的数据量，给出一个最佳的TableOption呢？
> > 
> > 
> > Good Idea，TiDB【SHARD_ROW_ID_BITS = 4 PRE_SPLIT_REGIONS = 4】作用于非整型主键或者没有主键表，直接根据数据量不好给建议，可以考虑非整型主键或者没有主键表统一带 TableOption
> 
> ORACLE中使用了复合主键的表是否可以直接映射为非聚簇表呢？然后添加上TableOption 。数据量这块确实不太好预估。

是否是非聚簇表取决于下游数据库，可以新增判断下游是 tidb 数据库且非整型主键或者没有主键表统一按照配置文件 tableOption 新增 option

**Comment by wentaojin** [comment]
> 

从时间上看不至于吧，空表运行 add index 这么久不符合预期，下游确认没问题嘛

**Comment by Lingoxu1990** [comment]
> > > ，下游确认没问题嘛
> > 
> > 
> > 我们有另一个tidb的测试集群，基本没有负载，空表建索引也要3秒（和社区其他人提出的问题一样）。 这个问题也不知道要多久才能修复，因此我建议目标库如果是TiDB，reverse生成的语句还是不要单独执行add index语句了。
> 
> 嗯，这个其实理解会更多下游数据库可能存在问题，从时间看超预期有点超预期，自测试一般是 <=1s 左右，会放入低优先级，优先其他事项，其他可以考虑改善这个

感谢！
