### ISSUE TITLE
gather阶段 索引长度3072限制的问题

### ISSUE THREAD

**Issue by Lingoxu1990** [wentaojin/transferdb#12]
oracle的字符串的长度是字节数，TiDB/Mysql是字符数。
同样的 
ctreate t1 (
col1  varchar(600),
col2  varcha(300),
primary key ( col1,col2)
)
这个表在gather阶段不会提示超长度，reverse阶段生成的 建表语句， 在TiDB/Mysql中执行会提示超过3072byte。
建议：根据目标库的编码，识别出上述问题。这样gather阶段的index长度限制识别才有效果

**Comment by wentaojin** [comment]
> oracle的字符串的长度是字节数，TiDB/Mysql是字符数。 同样的 ctreate t1 ( col1 varchar(600), col2 varcha(300), primary key ( col1,col2) ) 这个表在gather阶段不会提示超长度，reverse阶段生成的 建表语句， 在TiDB/Mysql中执行会提示超过3072byte。 建议：根据目标库的编码，识别出上述问题。这样gather阶段的index长度限制识别才有效果

ye，有道理，考虑 reverser 统一转换 utf8mb4，这块实现考虑在 gather 阶段索引长度这块按照编码成一定系数 * 4

**Comment by Lingoxu1990** [comment]
> > oracle的字符串的长度是字节数，TiDB/Mysql是字符数。 同样的 ctreate t1 ( col1 varchar(600), col2 varcha(300), primary key ( col1,col2) ) 这个表在gather阶段不会提示超长度，reverse阶段生成的 建表语句， 在TiDB/Mysql中执行会提示超过3072byte。 建议：根据目标库的编码，识别出上述问题。这样gather阶段的index长度限制识别才有效果
> 
> ye，有道理，考虑 reverser 统一转换 utf8mb4，这块实现考虑在 gather 阶段索引长度这块按照编码成一定系数 * 4

nice，感谢！
