### ISSUE TITLE
数据库查询结果自动判断数据类型出现异常

### ISSUE THREAD

**Issue by Lingoxu1990** [wentaojin/transferdb#13]
`func (e *Engine) GetOracleTableRows(querySQL string) ([]string, []interface{}, error)方法中的以下代码段
````
switch columnTypes[i] {
				case "int64":
					r, err := utils.StrconvIntBitSize(string(raw), 64)
					if err != nil {
						return cols, rowsResult, err
					}
					rowsResult = append(rowsResult, r)
				case "uint64":
					r, err := utils.StrconvUintBitSize(string(raw), 64)
					if err != nil {
						return cols, rowsResult, err
					}
					rowsResult = append(rowsResult, r)
				case "float32":
					r, err := utils.StrconvFloatBitSize(string(raw), 32)
					if err != nil {
						return cols, rowsResult, err
					}
					rowsResult = append(rowsResult, r)
				case "float64":
					r, err := utils.StrconvFloatBitSize(string(raw), 64)
					if err != nil {
						return cols, rowsResult, err
					}
					rowsResult = append(rowsResult, r)
				case "rune":
					r, err := utils.StrconvRune(string(raw))
					if err != nil {
						return cols, rowsResult, err
					}
					rowsResult = append(rowsResult, r)
				default:
					ok := utils.IsNum(string(raw))//  建议排除字符类型 ，字符大对象类型
					if ok {
						r, err := decimal.NewFromString(string(raw))
						if err != nil {
							return cols, rowsResult, err
						}
						if r.IsInteger() {
							r, err := utils.StrconvIntBitSize(string(raw), 64)
							if err != nil {
								return cols, rowsResult, err
							}
							rowsResult = append(rowsResult, r)
						} else {
							r, err := utils.StrconvFloatBitSize(string(raw), 64)
							if err != nil {
								return cols, rowsResult, err
							}
							rowsResult = append(rowsResult, r)
						}
					} else {
						rowsResult = append(rowsResult, string(raw))
					}

```
当字段类型已明确不是数值型类型的时候，不建议尝试转化为数值型的变量。
在我们的系统中，某些字段使用多个包含业务意义的数字拼接而成的字符串。在go环境中强制转化为数值型变量，会有超长度的风险。
例如我们这边在使用的时候就出现了以下的异常：
 **strconv.ParseInt:parsing \"33510300280000000012\":value out of range**

**Comment by wentaojin** [comment]
> `func (e *Engine) GetOracleTableRows(querySQL string) ([]string, []interface{}, error)方法中的以下代码段
> 
> ```
> switch columnTypes[i] {
> 				case "int64":
> 					r, err := utils.StrconvIntBitSize(string(raw), 64)
> 					if err != nil {
> 						return cols, rowsResult, err
> 					}
> 					rowsResult = append(rowsResult, r)
> 				case "uint64":
> 					r, err := utils.StrconvUintBitSize(string(raw), 64)
> 					if err != nil {
> 						return cols, rowsResult, err
> 					}
> 					rowsResult = append(rowsResult, r)
> 				case "float32":
> 					r, err := utils.StrconvFloatBitSize(string(raw), 32)
> 					if err != nil {
> 						return cols, rowsResult, err
> 					}
> 					rowsResult = append(rowsResult, r)
> 				case "float64":
> 					r, err := utils.StrconvFloatBitSize(string(raw), 64)
> 					if err != nil {
> 						return cols, rowsResult, err
> 					}
> 					rowsResult = append(rowsResult, r)
> 				case "rune":
> 					r, err := utils.StrconvRune(string(raw))
> 					if err != nil {
> 						return cols, rowsResult, err
> 					}
> 					rowsResult = append(rowsResult, r)
> 				default:
> 					ok := utils.IsNum(string(raw))//  建议排除字符类型 ，字符大对象类型
> 					if ok {
> 						r, err := decimal.NewFromString(string(raw))
> 						if err != nil {
> 							return cols, rowsResult, err
> 						}
> 						if r.IsInteger() {
> 							r, err := utils.StrconvIntBitSize(string(raw), 64)
> 							if err != nil {
> 								return cols, rowsResult, err
> 							}
> 							rowsResult = append(rowsResult, r)
> 						} else {
> 							r, err := utils.StrconvFloatBitSize(string(raw), 64)
> 							if err != nil {
> 								return cols, rowsResult, err
> 							}
> 							rowsResult = append(rowsResult, r)
> 						}
> 					} else {
> 						rowsResult = append(rowsResult, string(raw))
> 					}
> 
> ```
> 当字段类型已明确不是数值型类型的时候，不建议尝试转化为数值型的变量。
> 在我们的系统中，某些字段使用多个包含业务意义的数字拼接而成的字符串。在go环境中强制转化为数值型变量，会有超长度的风险。
> 例如我们这边在使用的时候就出现了以下的异常：
>  **strconv.ParseInt:parsing \"33510300280000000012\":value out of range**
> ```

嗯，当时考虑可能潜在其他数值类型存在，下个版本去除，直接 default rowsResult = append(rowsResult, string(raw)) 当作字符串处理
