### ISSUE TITLE
调用full任务，date类型数据转换到mysql报错

### ISSUE THREAD

**Issue by 154650362** [wentaojin/transferdb#14]
您好，在测试的时候发现某个oracle字段类型是date。在调用full的时候转换的日期格式和mysql的datetime不匹配
sync oracle table rows by checkpoint failed: sync oracle table rows by rowid failed, error: single full table [TODB.MARVIN3] data concurrency bulk insert mysql falied: single full table [TODB.MARVIN3] sql [REPLACE INTO TODB.MARVIN3 (ID,INC_DATETIME,RANDOM_ID,RANDOM_STRING) VALUES (1,'2022-04-20T16:36:24+08:00',74,'QIECOW677Q8LIECYQR33'),(2,'2022-04-20T16:36:25+08:00',75,'9KC8RGDA1T170KE8NZ14'),。。。
Incorrect datetime value: '2022-04-20T16:36:24+08:00' for column 'INC_DATETIME' 
oracle 版本 11.2.0.1.0

**Comment by wentaojin** [comment]
> 您好，在测试的时候发现某个oracle字段类型是date。在调用full的时候转换的日期格式和mysql的datetime不匹配 sync oracle table rows by checkpoint failed: sync oracle table rows by rowid failed, error: single full table [TODB.MARVIN3] data concurrency bulk insert mysql falied: single full table [TODB.MARVIN3] sql [REPLACE INTO TODB.MARVIN3 (ID,INC_DATETIME,RANDOM_ID,RANDOM_STRING) VALUES (1,'2022-04-20T16:36:24+08:00',74,'QIECOW677Q8LIECYQR33'),(2,'2022-04-20T16:36:25+08:00',75,'9KC8RGDA1T170KE8NZ14'),。。。 Incorrect datetime value: '2022-04-20T16:36:24+08:00' for column 'INC_DATETIME' oracle 版本 11.2.0.1.0

试下配置文件 [target] connect-params 连接串内新增  parseTime=True&loc=Local 看下呢

**Comment by 154650362** [comment]
"connect-params": "charset=utf8mb4&multiStatements=true&parseTime=true&loc=Local",
改成了这样，仍然不行，
还是报一样的错
 data bulk insert mysql falied: Error 1292: Incorrect datetime value: '2022-04-20T16:36:24+08:00' for column 'INC_DATETIME' at row 1
oracle的测试数据是通过
random_table_data.sh 这个脚本生成的

**Comment by wentaojin** [comment]
> "connect-params": "charset=utf8mb4&multiStatements=true&parseTime=true&loc=Local",
> 改成了这样，仍然不行，
> 还是报一样的错
> data bulk insert mysql falied: Error 1292: Incorrect datetime value: '2022-04-20T16:36:24+08:00' for column 'INC_DATETIME' at row 1
> oracle的测试数据是通过

好的，我复现看下

**Comment by wentaojin** [comment]
> 2022-04-20T16:36:24+08:00

**Comment by 154650362** [comment]
您好，配置如下
 "source": {
		"username": "test",
		"password": "test",
		"host": "101.XXX.XXX.166",
		"port": 1521,
		"service-name": "helowin",
		"connect-params": "poolMinSessions=10&poolMaxSessions=1000&poolWaitTimeout=60s&poolSessionMaxLifetime=1h&poolSessionTimeout=5m&poolIncrement=10&timezone=Local",
		"session-params": ["alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss'"],
		"schema-name": "SH",
		"include-table": ["CUSTOMERS"],
		"exclude-table": []
	},

**Comment by wentaojin** [comment]
> ```
> 您好，配置如下
> ```
> 
> "source": { "username": "test", "password": "test", "host": "101.XXX.XXX.166", "port": 1521, "service-name": "helowin", "connect-params": "poolMinSessions=10&poolMaxSessions=1000&poolWaitTimeout=60s&poolSessionMaxLifetime=1h&poolSessionTimeout=5m&poolIncrement=10&timezone=Local", "session-params": ["alter session set nls_date_format = 'yyyy-mm-dd hh24:mi:ss'"], "schema-name": "SH", "include-table": ["CUSTOMERS"], "exclude-table": [] },

sry，同样的 oracle 版本 11.2.0.1.0 同样模拟数据脚本，没有复现可以正常 run，想问下运行程序是编译的最新的二进制文件嘛或者必现的不，可以尝试最新二进制文件看下
![image](https://user-images.githubusercontent.com/34805682/164953394-a5777b5c-9bad-4027-b4a6-e6ff0db9a8c6.png)

**Comment by 154650362** [comment]
这里的数据生成会变成2022-04-20T16:36:24+08:00这种格式的数据，
但因为oracle中的date类型前面通过reverse被转化为mysql的datetime字段类型，
组装的replace into语句插入mysql就会报
insert mysql falied: Error 1292: Incorrect datetime value: '2022-04-20T16:36:24+08:00' for column
这样的错误

暂时通过	service/engine.go
修改GetOracleTableRows方法增加如下代码来处理，不知是否妥当：

			case "sql.NullTime":
		         t, err := time.ParseInLocation("2006-01-02T15:04:05+08:00", string(raw), time.Local)
					if err != nil {
						return cols, batchResults, err
					}
					r := t.Format("2006-01-02 15:04:05")
					rowsResult = append(rowsResult, fmt.Sprintf("'%v'", r))

**Comment by wentaojin** [comment]
> 这里的数据生成会变成2022-04-20T16:36:24+08:00这种格式的数据， 但因为oracle中的date类型前面通过reverse被转化为mysql的datetime字段类型， 组装的replace into语句插入mysql就会报 insert mysql falied: Error 1292: Incorrect datetime value: '2022-04-20T16:36:24+08:00' for column 这样的错误
> 
> 暂时通过 service/engine.go 修改GetOracleTableRows方法增加如下代码来处理，不知是否妥当：
> 
> ```
> 		case "sql.NullTime":
> 	         t, err := time.ParseInLocation("2006-01-02T15:04:05+08:00", string(raw), time.Local)
> 				if err != nil {
> 					return cols, batchResults, err
> 				}
> 				r := t.Format("2006-01-02 15:04:05")
> 				rowsResult = append(rowsResult, fmt.Sprintf("'%v'", r))
> ```

sry，是我误解了，tidb 是可以的，mysql 刚试了下确实会报错，直接按照 sql.NullTime 可能会有问题，oracle date->datetime 没问题，但是 oracle timestamp(9) -> timestamp(6) 那么精读会缺失，这块得考虑真实数据类型来看
