### ISSUE TITLE
 Oracle 数据库 ->postgresql

### ISSUE THREAD

**Issue by gleke** [wentaojin/transferdb#23]
Oracle  ->postgresql

**Comment by gleke** [comment]
现在支持Oracle ->postgresql？

**Comment by wentaojin** [comment]
现在还不支持，未来计划优先支持oracle number 数据类型扫描以及 pg -> mysql 结构转换，参见 https://github.com/wentaojin/dbms，考虑在新仓库提交需求，有类似需求下会考虑实现
