### ISSUE TITLE
提供一个后台来设置同步的源表字段和目标表字段的映射关系，包括数据类型转换，值的转换

### ISSUE THREAD

**Issue by gleke** [wentaojin/transferdb#24]
提供一个后台来设置同步的源表字段和目标表字段的映射关系，包括数据类型转换，值的转换

**Comment by wentaojin** [comment]
> 提供一个后台来设置同步的源表字段和目标表字段的映射关系，包括数据类型转换，值的转换

@gleke 源表字段以及目标表字段映射关系自定义功能现已具备（可以参看下使用手册），值的转换是指什么

**Comment by gleke** [comment]
源值为"A",同步到目标需要转换为"B"

**Comment by wentaojin** [comment]
> 数据同步过程中经常发现，ORACLE记录在内存中产生，但是并没写入数据库表，如果只是读取数据库表中的记录会导致部分数据丢失，同步的规则：每10秒去读取最新生成的100条记录

什么模式下运行的

**Comment by gleke** [comment]
这个有模式区分？都会出现，因为内存的数据没有写入数据库表，同步数据库表的数据是得不到数据的

**Comment by gleke** [comment]
联系qq:237401117

**Comment by wentaojin** [comment]
长时间未回复 closed

源值为"A",同步到目标需要转换为"B",转换规则按需求设置，可以加字符串的运算，清空前后空格，前后添加固定前缀等
------
关于这个需求，麻烦单独开个 ISSUE 记录
