### ISSUE TITLE
Oracle 的联合主键转成MySQL时列明重复

### ISSUE THREAD

**Issue by skyecool** [wentaojin/transferdb#27]
-- Oracle    
constraint ABC_PK
        primary key (A_NO, B_NO, C_NO)

-- 转成MySQL 后 联合主键列重复了
PRIMARY KEY (`A_NO`,`A_NO`,`B_NO`,`B_NO`,`C_NO`,`C_NO`)

**Comment by skyecool** [comment]
同时存在 constraint 和 primary key 会重复

**Comment by wentaojin** [comment]
@skyecool 当前使用的版本是哪个版本，这个问题是修复了的
