### ISSUE TITLE
列定义default部分存在 ('03'), 转换后TIDB会报错

### ISSUE THREAD

**Issue by Chad20N13** [wentaojin/transferdb#30]
oracle列定义default 部分存在('03')，转换到TIDB运行时会报错；
需要考虑转换为： '03'， 去除掉括号。

**Comment by wentaojin** [comment]
> oracle列定义default 部分存在('03')，转换到TIDB运行时会报错； 需要考虑转换为： '03'， 去除掉括号。
O2T
CREATE TABLE xiamen7 (
	id VARCHAR ( 10 ),
	name1 NUMBER DEFAULT ( 7 ),
	name2 VARCHAR2 ( 10 ) DEFAULT ( 'po' ),
	name3 NUMBER DEFAULT ( '90' ),
  age int 
);

------
CREATE TABLE `MARVIN`.`XIAMEN7` (
`ID` VARCHAR(10) COLLATE utf8mb4_bin,
`NAME1` DECIMAL(65,30) DEFAULT 7,
`NAME2` VARCHAR(10) COLLATE utf8mb4_bin DEFAULT 'po',
`NAME3` DECIMAL(65,30) DEFAULT '90',
`AGE` DECIMAL(38)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin SHARD_ROW_ID_BITS = 4 PRE_SPLIT_REGIONS = 4;
