### ISSUE TITLE
pk/uk/index number datatype column isn't exist, please skip or fixed"

### ISSUE THREAD

**Issue by skyecool** [wentaojin/transferdb#34]
问题一：执行比对报错

./transferdb --mode compare --config  xxx_config.toml

table [yyy]

"DICT_SORT" NUMBER(*,0)

[FATAL]	[cmd/main.go:59]	server run failed	{"error": "oracle schema [xxx] table [yyy] pk/uk/index number datatype column isn't exist, please skip or fixed"}

问题二：执行check 报错

EXPRESSION  -- 是MySQL 8.0 的字段， 5.7 不兼容

[FATAL]	[cmd/main.go:59]	server run failed	{"error": "[TYPE] transferdb [DOMAIN]: check [CAUSE]: general sql [SELECT \n\t\tINDEX_NAME,\n\t\tINDEX_TYPE,\n\t\tIFNULL(EXPRESSION,'') COLUMN_EXPRESSION,\n\t\tIF(NON_UNIQUE=1,\"NONUNIQUE\",\"UNIQUE\") AS UNIQUENESS,\n       GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',') AS COLUMN_LIST\nFROM INFORMATION_SCHEMA.STATISTICS\nWHERE \n  INDEX_NAME NOT IN ('PRIMARY','UNIQUE')\n  AND UPPER(TABLE_SCHEMA) = UPPER('xxx')\n  AND UPPER(TABLE_NAME) = UPPER('yyy')\nGROUP BY INDEX_NAME,UNIQUENESS,INDEX_TYPE,COLUMN_EXPRESSION] query failed: [Error 1054: Unknown column 'EXPRESSION' in 'field list']"}

**Comment by wentaojin** [comment]
问题二是说 O-> MySQL 8.0 因为 EXPRESSION 字段 check 报错嘛

**Comment by skyecool** [comment]
> 问题二是说 O-> MySQL 8.0 因为 EXPRESSION 字段 check 报错嘛

O->MySQL 5.7 报错，报 EXPRESSION 字段不存在

**Comment by wentaojin** [comment]
上下游表结构方便 share 下

**Comment by wentaojin** [comment]
关于问题二，方便 share 下表结构用于复现，问题一 compare 前提是需要表存在主键/唯一约束/唯一索引，且表存number 类型字段是最低条件是带有索引的字段，看报错 number 类型字段没有索引

**Comment by skyecool** [comment]
元数据表 INFORMATION_SCHEMA.STATISTICS 8.0 与5.7 字段不太一样 8.0 的有 EXPRESSION 这个字段， 5.7 没有这个字段

MySQL 8.0 
mysql> desc INFORMATION_SCHEMA.STATISTICS;
+---------------+---------------+------+-----+---------+-------+
| Field         | Type          | Null | Key | Default | Extra |
+---------------+---------------+------+-----+---------+-------+
| TABLE_CATALOG | varchar(64)   | NO   |     | NULL    |       |
| TABLE_SCHEMA  | varchar(64)   | NO   |     | NULL    |       |
| TABLE_NAME    | varchar(64)   | NO   |     | NULL    |       |
| NON_UNIQUE    | int           | NO   |     | 0       |       |
| INDEX_SCHEMA  | varchar(64)   | NO   |     | NULL    |       |
| INDEX_NAME    | varchar(64)   | YES  |     | NULL    |       |
| SEQ_IN_INDEX  | int unsigned  | NO   |     | NULL    |       |
| COLUMN_NAME   | varchar(64)   | YES  |     | NULL    |       |
| COLLATION     | varchar(1)    | YES  |     | NULL    |       |
| CARDINALITY   | bigint        | YES  |     | NULL    |       |
| SUB_PART      | bigint        | YES  |     | NULL    |       |
| PACKED        | binary(0)     | YES  |     | NULL    |       |
| NULLABLE      | varchar(3)    | NO   |     |         |       |
| INDEX_TYPE    | varchar(11)   | NO   |     |         |       |
| COMMENT       | varchar(8)    | NO   |     |         |       |
| INDEX_COMMENT | varchar(2048) | NO   |     | NULL    |       |
| IS_VISIBLE    | varchar(3)    | NO   |     |         |       |
**| EXPRESSION    | longtext      | YES  |     | NULL    |       |**
+---------------+---------------+------+-----+---------+-------+
18 rows in set (0.05 sec)

MySQL5.7 

mysql> desc INFORMATION_SCHEMA.STATISTICS;
+---------------+---------------+------+-----+---------+-------+
| Field         | Type          | Null | Key | Default | Extra |
+---------------+---------------+------+-----+---------+-------+
| TABLE_CATALOG | varchar(512)  | NO   |     |         |       |
| TABLE_SCHEMA  | varchar(64)   | NO   |     |         |       |
| TABLE_NAME    | varchar(64)   | NO   |     |         |       |
| NON_UNIQUE    | bigint(1)     | NO   |     | 0       |       |
| INDEX_SCHEMA  | varchar(64)   | NO   |     |         |       |
| INDEX_NAME    | varchar(64)   | NO   |     |         |       |
| SEQ_IN_INDEX  | bigint(2)     | NO   |     | 0       |       |
| COLUMN_NAME   | varchar(64)   | NO   |     |         |       |
| COLLATION     | varchar(1)    | YES  |     | NULL    |       |
| CARDINALITY   | bigint(21)    | YES  |     | NULL    |       |
| SUB_PART      | bigint(3)     | YES  |     | NULL    |       |
| PACKED        | varchar(10)   | YES  |     | NULL    |       |
| NULLABLE      | varchar(3)    | NO   |     |         |       |
| INDEX_TYPE    | varchar(16)   | NO   |     |         |       |
| COMMENT       | varchar(16)   | YES  |     | NULL    |       |
| INDEX_COMMENT | varchar(1024) | NO   |     |         |       |
+---------------+---------------+------+-----+---------+-------+
16 rows in set (0.00 sec)

**Comment by skyecool** [comment]
> 关于问题二，方便 share 下表结构用于复现，问题一 compare 前提是需要表存在主键/唯一约束/唯一索引，且表存number 类型字段是最低条件是带有索引的字段，看报错 number 类型字段没有索引

pk/uk/index number datatype column isn't exist, please skip or fixed
这个是只支持 有number字段类型的主键或者唯一索引/索引 进行数据比对吗， varchar类型的主键、唯一索引不支持比对是吗

**Comment by wentaojin** [comment]
@skyecool 问题二表结构 show create table 输出比较好，这样好直接创建，关于数据对比，文档有标注：
1、表上有主键/唯一索引（可以是整型也可以是字符型）
2、表上需要有 number 类型字段，表上需要有索引，这个索引可以是 PK/UK/普通

**Comment by wentaojin** [comment]
> > 关于问题二，方便 share 下表结构用于复现，问题一 compare 前提是需要表存在主键/唯一约束/唯一索引，且表存number 类型字段是最低条件是带有索引的字段，看报错 number 类型字段没有索引
> 
> pk/uk/index number datatype column isn't exist, please skip or fixed 这个是只支持 有number字段类型的主键或者唯一索引/索引 进行数据比对吗， varchar类型的主键、唯一索引不支持比对是吗

关于数据对比，文档有标注：
1、表上有主键/唯一索引（可以是整型也可以是字符型）
2、表上需要有 number 类型字段，表上需要有索引，这个索引可以是 PK/UK/普通

**Comment by skyecool** [comment]
> > > 关于问题二，方便 share 下表结构用于复现，问题一 compare 前提是需要表存在主键/唯一约束/唯一索引，且表存number 类型字段是最低条件是带有索引的字段，看报错 number 类型字段没有索引
> > 
> > 
> > pk/uk/index number datatype column isn't exist, please skip or fixed 这个是只支持 有number字段类型的主键或者唯一索引/索引 进行数据比对吗， varchar类型的主键、唯一索引不支持比对是吗
> 
> 关于数据对比，文档有标注： 1、表上有主键/唯一索引（可以是整型也可以是字符型） 2、表上需要有 number 类型字段，表上需要有索引，这个索引可以是 PK/UK/普通

有主键情况下可以进行比对吗，不是number字段 或者number字段没有索引的情况
