### ISSUE TITLE
VARCHAR2 o2m的转化字段长度取dba_tab_columns中的CHAR_LENGTH 貌似更合理些

### ISSUE THREAD

**Issue by skyecool** [wentaojin/transferdb#35]
-- o
"A_NAME" VARCHAR2(512 CHAR)
-- o2m
`A_NAME` VARCHAR(2048) COMMENT 'yyy',

select table_name,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,DEFAULT_LENGTH,DATA_DEFAULT,CHAR_LENGTH from dba_tab_columns where table_name='xxxx';

TABLE_NAME		       COLUMN_NAME		      DATA_TYPE       DATA_LENGTH DEFAULT_LENGTH DATA_DEFAULT	      CHAR_LENGTH
------------------------------ ------------------------------ --------------- ----------- -------------- -------------------- -----------
xxxx   A_NAME 		      VARCHAR2		     2048					      512

**Comment by wentaojin** [comment]
CHAR_LENGTH 应该针对的是字符数据类型 CHAR 的，目前没考虑，统一取得 DATA_LENGTH，如果是 Bytes 取 CHAR_LENGTH 有问题，需要看下有什么方式区分字符数据类型是 CHAR 还是 Bytes 来看取哪个字段会比较好
