### ISSUE TITLE
数据校验比对可否用主键分批chunk读取进行比对

### ISSUE THREAD

**Issue by skyecool** [wentaojin/transferdb#38]
数据校验比对可否用主键分批读取进行比对，比如gorose chunk 的方式全表读取，以主键/唯一键/唯一索引 + NUMBER 类型字段 的列进行chunk 有点局限性，有很大一部分表不能满足这个要求
通过 DBMS_PARALLEL_EXECUTE.CREATE_CHUNKS_BY_NUMBER_COL 进行chunk ,对于只读的账号进行数据比对有点困难哈

https://github.com/gohouse/gorose#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95

 User := db.Table("users")
 User.Fields("id, name").Where("id",">",2).Chunk(2, func(data []gorose.Data) error {
     // for _,item := range data {
     // 	   fmt.Println(item)
     // }
     fmt.Println(data)
     
     // 这里不要忘记返回错误或nil
     return nil
 })

**Comment by wentaojin** [comment]
版本重构ing，未来会废弃该方式，采用统计信息划分用于对比

**Comment by wentaojin** [comment]
该功能已在 https://github.com/wentaojin/dbms 仓库实现
