### ISSUE TITLE
有无详细一点的文档？

### ISSUE THREAD

**Issue by gleke** [wentaojin/transferdb#6]
很好的项目，最近工作的原因接触到数据的导入，ORACLE导入到POSTGRESQL,希望本项目能提供帮助

**Comment by gleke** [comment]
建个微信群，大家交流一下

**Comment by wentaojin** [comment]
> 很好的项目，最近工作的原因接触到数据的导入，ORACLE导入到POSTGRESQL,希望本项目能提供帮助

ORACLE -> POSTGRESQL 相关功能目前不支持，相关文档使用链接参见 https://github.com/wentaojin/transferdb/blob/main/docs/user_guaid.md ，不知道该文档是否可以帮助到你或者说【详细一点】的文档方便的话麻烦具体些，谢谢

**Comment by gleke** [comment]
你这个文档看了，还是没太明白，能不能举一个例子，同步数据库中一个表，如何设置同步规则

**Comment by wentaojin** [comment]
> 你这个文档看了，还是没太明白，能不能举一个例子，同步数据库中一个表，如何设置同步规则

同步规则是没有自定义同步规则，目前只支持上游数据回放，即数据是怎么样的就怎么样回放，具体设置哪些表同步取决于配置文件：
include-table = []
exclude-table = []

**Comment by wentaojin** [comment]
> 你这个文档看了，还是没太明白，能不能举一个例子，同步数据库中一个表，如何设置同步规则
同步规则是没有自定义同步规则，目前只支持上游数据回放，即数据是怎么样的就怎么样回放，具体设置哪些表同步取决于配置文件：
include-table = []
exclude-table = []

**Comment by wentaojin** [comment]
长期未回复，close
