### ISSUE TITLE
解压的压缩包

### ISSUE THREAD

**Issue by SteveCris** [wentaojin/transferdb#62]
执行  ./transferdb-v1.0.22-linux-amd64  -config config.toml  -mode reverse -source oracle -target  mysql/tidb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1377f64]

goroutine 1 [running]:
github.com/wentaojin/transferdb/server.IReverse({0x1929690, 0xc0000440a0}, 0xc000100400)
        /source/server/reverse.go:58 +0x244
github.com/wentaojin/transferdb/server.Run({0x1929690, 0xc0000440a0}, 0xc000100400)
        /source/server/server.go:44 +0x248
main.main()
        /source/cmd/main.go:58 +0x12a

**Comment by SteveCris** [comment]
麻烦解答下 为啥执行该条命令 出现   error: invalid memory address or nil pointer dereference

**Comment by wentaojin** [comment]
target 指定 mysql 或 tidb ，非两个都指定
