### ISSUE TITLE
Transferdb能做 sql server 转换到 TiDB 或者 Mysql?

### ISSUE THREAD

**Issue by SteveCris** [wentaojin/transferdb#64]
transferdb  支持Sqlserver 异构数据库 schema 转换、全量数据增量数据到 Mysql 或者 TiDB, 不行的话，有什么好的工具做吗

**Comment by wentaojin** [comment]
no，currently it's not support，you can search other solution at the website

**Comment by SteveCris** [comment]
好的！ 谢谢
