### ISSUE TITLE
ORA-12545: Connect failed because target host or object does not exist

### ISSUE THREAD

**Issue by wakaka2019** [wentaojin/transferdb#7]
![image](https://user-images.githubusercontent.com/65145640/156680298-af64daa4-88b0-416c-a501-a980f65b9782.png)

配置了tnsnames.ora，sqlplus能连接，程序报错ORA-12545: Connect failed because target host or object does not exist

**Comment by wentaojin** [comment]
> ![image](https://user-images.githubusercontent.com/65145640/156680298-af64daa4-88b0-416c-a501-a980f65b9782.png)
> 
> 配置了tnsnames.ora，sqlplus能连接，程序报错ORA-12545: Connect failed because target host or object does not exist

想问下配置文件 service-name 配置的是服务名还是实例 Sid 名呢

**Comment by wentaojin** [comment]
长期未回复，closed
