### ISSUE TITLE
同一个schema下面有两个同名的表（大小写不同），会触发comments exist multiple values

### ISSUE THREAD

**Issue by wuchao-pingcap** [wentaojin/transferdb#75]
报错信息：
get table info failed: oracle schema [NEWCLAIMUSER] table [FLYWAY_SCHEMA_HISTORY] comments exist multiple values: [[map[COMMENTS: TABLE_NAME:FLYWAY_SCHEMA_HISTORY TABLE_TYPE:TABLE] map[COMMENTS: TABLE_NAME:flyway_schema_history TABLE_TYPE:TABLE]]]

原因分析：
同一个schema下面有两个同名的表，一个大写，一个小写。

dba_tab_comments表里有两条记录
select table_name,table_type,comments 
from dba_tab_comments 
where 
table_type = 'TABLE'
and upper(owner)=upper('NEWCLAIMUSER')
and upper(table_name)=upper('FLYWAY_SCHEMA_HISTORY')

![20231212-142532](https://github.com/wentaojin/transferdb/assets/105029637/d86c7b92-a653-4880-ad60-9cda6ef99333)

**Comment by wentaojin** [comment]
![ForjNSkhNA](https://github.com/wentaojin/transferdb/assets/34805682/f49a5d35-5e57-4c50-b010-b0ee8f34a318)
mysql / tidb 表名不区分大小写
