### ISSUE TITLE
关于字符长度的转换控制建议

### ISSUE THREAD

**Issue by Lingoxu1990** [wentaojin/transferdb#9]
背景：
我们的系统迁移改造是按组件开展的，在切换的过程中，存在这种情况：部分未改造的组件仍然沿用oracle，改造后的组件使用tidb。
由于组件之间存在日终的数据交换。因此存在tidb数据日终传输至oracle的需求。

问题：
由于oracle的varchar2类型的长度是字节，而tidb是字符。直接使用转换工具生成的建表语句，可能会导致下游使用oracle的组件，在数据加载的时候报错。

建议：
能否识别出oralce的varchar/varchar2类型中是否包含中文字符，如果包含中文字符，根据下游编码，调整其目标ddl的varchar长度？

**Comment by wentaojin** [comment]
> 背景： 我们的系统迁移改造是按组件开展的，在切换的过程中，存在这种情况：部分未改造的组件仍然沿用oracle，改造后的组件使用tidb。 由于组件之间存在日终的数据交换。因此存在tidb数据日终传输至oracle的需求。
> 
> 问题： 由于oracle的varchar2类型的长度是字节，而tidb是字符。直接使用转换工具生成的建表语句，可能会导致下游使用oracle的组件，在数据加载的时候报错。
> 
> 建议： 能否识别出oralce的varchar/varchar2类型中是否包含中文字符，如果包含中文字符，根据下游编码，调整其目标ddl的varchar长度？

这个问题确实存在，不过只有 tidb 回写 oracle 才存在，但表结构转换并不能识别到真实数据是否存在中文（除非去访问，这样代价太大不可取），目前我还没想到什么方式，不知道您那边是否有什么方式可以识别？

**Comment by Lingoxu1990** [comment]
> > 背景： 我们的系统迁移改造是按组件开展的，在切换的过程中，存在这种情况：部分未改造的组件仍然沿用oracle，改造后的组件使用tidb。 由于组件之间存在日终的数据交换。因此存在tidb数据日终传输至oracle的需求。
> > 问题： 由于oracle的varchar2类型的长度是字节，而tidb是字符。直接使用转换工具生成的建表语句，可能会导致下游使用oracle的组件，在数据加载的时候报错。
> > 建议： 能否识别出oralce的varchar/varchar2类型中是否包含中文字符，如果包含中文字符，根据下游编码，调整其目标ddl的varchar长度？
> 
> 这个问题 tidb 回写 oracle 是存在的，但表结构转换并不能识别到真实数据是否存在中文（除非去访问，这样代价太大不可取），目前我还没想到什么方式，不知道您那边是否有什么方式可以识别？

目前我也没有什么好的办法来识别。只能先用工具中的db_mata.column_rule_map表来做一个强制映射了。
